services:
  nuedb:
    image: ajax16/nuedb:latest
    ports:
      - 4300:4300
    environment:
      NUEDB_ROOT_USERNAME: angular
      NUEDB_ROOT_PASSWORD: angular
    restart: always
    volumes:
      - 'data:/var/nuedb'

volumes:
  data: